/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  // tutorialSidebar: [{
  //     type: 'category',
  //     label: 'React',
  //     items: ['react'],
  // }, ],
  reactSideBar: [
      {
          type: 'autogenerated',
          dirName: 'react',
      },
  ],
  deep_learning: [
      {
          type: 'category',
          label: '基础知识',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'deep_learning/基础知识'
              },
          ],
      },
      {
          type: 'category',
          label: '目标检测',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'deep_learning/目标检测'
              },
          ],
      },
      {
        type: 'category',
        label: '图像分割',
        items: [
            {
                type: 'autogenerated',
                dirName: 'deep_learning/图像分割'
            },
        ],
      },
      {
        type: 'category',
        label: '视觉异常检测',
        items: [
            {
                type: 'autogenerated',
                dirName: 'deep_learning/视觉异常检测'
            },
        ],
    },
      {
          type: 'category',
          label: '可信机器学习',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'deep_learning/可信机器学习'
              },
          ],
      },
      {
        type: 'category',
        label: '统计计算与机器学习',
        items: [
            {
                type: 'autogenerated',
                dirName: 'deep_learning/统计计算与机器学习'
            },
        ],
    },
  ],
  math: [
      {
          type: 'autogenerated',
          dirName: 'math',
      },
  ],
  algorithm: [
      {
          type: 'autogenerated',
          dirName: 'algorithm',
      },
  ],
  courses: [
      {
          type: 'category',
          label: '操作系统',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'courses/操作系统'
              },
          ],
      },
      {
          type: 'category',
          label: '计算机网络',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'courses/计算机网络'
              },
          ],
      },
      {
          type: 'category',
          label: '逆向工程',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'courses/逆向工程'
              },
          ],
      },
      {
          type: 'category',
          label: '信息安全数学基础',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'courses/信息安全数学基础'
              },
          ],
      },
      {
          type: 'category',
          label: '网络渗透测试',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'courses/网络渗透测试'
              },
          ],
      },
      {
          type: 'category',
          label: '数据库',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'courses/数据库'
              },
          ],
      },
      {
          type: 'category',
          label: '系统安全',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'courses/系统安全'
              },
          ],
      },
      {
          type: 'category',
          label: '网络安全技术',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'courses/网络安全技术'
              },
          ],
      },
      {
        type: 'category',
        label: '其他课程',
        items: [
            {
                type: 'autogenerated',
                dirName: 'courses/其他课程'
            },
        ],
    }
  ],
  others: [
      {
          type: 'category',
          label: '环境保护大使',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'others/环境保护大使'
              },
          ],
      },
      {
          type: 'category',
          label: '论文写作技巧',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'others/论文写作技巧'
              },
          ],
      },
      {
          type: 'category',
          label: '前后端',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'others/前后端'
              },
          ],
      },
      {
        type: 'category',
        label: '爬虫',
        items: [
            {
                type: 'autogenerated',
                dirName: 'others/爬虫'
            },
        ],
      },
      {
          type: 'category',
          label: '小工具',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'others/小工具'
              },
          ],
      },
      {
          type: 'category',
          label: 'English',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'others/English'
              },
          ],
      },
  ]
};

module.exports = sidebars;